### ISSUE TITLE
Checkbox and radio validation

### ISSUE THREAD

**Issue by volodymyrl** [navjobs/validify#16]
If I add input type='checkbox' or input type='radio' inside <Form> component it return empty string as a value

**Comment by zackify** [comment]
It puts an empty string so that there isn't an uncontrolled react warning. If you want nothing as the value initially, this should work:

```js
export default ({ error,value, ...props }) => {
  return (
    <div>
      <p>{error}</p>
      <input {...props} value={value || null} />
    </div>
  );
};
```

**Comment by volodymyrl** [comment]
> It puts an empty string so that there isn't an uncontrolled react warning. 
I mean it return an empty string for checkbox in onValues trigger, it should return is it checked ( true or false) for this input type. But it's try take input value.

**Comment by zackify** [comment]
I think I fixed this, can you install the latest version and close this if so? https://github.com/navjobs/validify/releases/tag/2.0.6

**Comment by audiolion** [comment]
The way I tackled this previously was adding an `onChange` handler

`onChange={e => props.onChange({ target: { name: props.name, value: e } })}` which would bubble up the event

**Comment by zackify** [comment]
@audiolion I added `e.target.checked || e.target.value` to the onChange. That should solve it

**Comment by volodymyrl** [comment]
@zackify thanks for quick updates. It works for checked state and return true, but for unchecked state it return a string "true". I think it will be better check input type and not target.checked, because for unchecked state this  target.checked || target.value;  will be always return input value 

I solved it for a now by updating onChange and checked props in Input component

```
<Input
      {...restProps}
      name={name}
      id={name}
      checked={restProps.value}
      onChange={({ target }) => {
        let { value } = target;
        if (target.type === 'radio' || target.type === 'checkbox') {
          value = target.checked;
        }
        return restProps.onChange({ target: { name, value } });
      }}
    />
```

**Comment by zackify** [comment]
I’ll fix it today. Sorry, a little hard to test perfectly inside the test env only. My bad

**Comment by zackify** [comment]
Should be working in 2.0.7. Added a couple more tests. Also, I dont really like how I did this. So if you can think of a cleaner way to check for false values send a PR :D https://github.com/navjobs/validify/commit/775b9e99705cc9f62eeca0e297cceb411245d7be

**Comment by volodymyrl** [comment]
@zackify Thanks for the fast fixes! I checked your code and don't know how to rewrite it better, because it has a lot conditions. In general I decide to use different validate components for text/number/phone and checkbox/radio inputs, because we need set checked props for them and it better for me use 2 simple component than add a lot conditions in one. And I think in the documentation should be information and example (like this that https://github.com/navjobs/validify/issues/16#issuecomment-329404983 ) your custom validate component should return standard event object {target: {name, value, checked} , additionally it will be useful for people who want validate some custom components like datepicker or autocomplete. Thanks for fast fixes one more time!

**Comment by zackify** [comment]
Thanks for the ideas I am going to think about it today and see what I come up with

**Comment by zackify** [comment]
Hmm, came up with this. it's a little better. https://github.com/navjobs/validify/commit/24f4cc421131d6a72f4015f237ed58eff5fd82cd Kind of wish we didnt support controlling the state AND passing the state to a higher level. wish we made that into a higher order component that does it for you. then only one value to check.
