### ISSUE TITLE
Values are not updated when typing

### ISSUE THREAD

**Issue by patrickedqvist** [navjobs/validify#17]
Using the provided example in the usage documentation the `value` in `Input` aren't updated when a user types. 

# Action
User types `abc`

# Expected behavior
Input `value` equals `abc` and the `onChange` event is fired

# Actual behavior
Input `value` is empty and the `onChange` event is not fired.

Tested on react `16.0.0` and `15.6.1`, with library `2.0.8`

See [example](https://codesandbox.io/s/zrppkvv4k3).

**Comment by zackify** [comment]
Sorry about this, messed up in the tests, assumed target.checked was null or undefined if an input isn't a checkbox. But that is not true. https://codesandbox.io/s/54roklyr9p Install 2.0.10!

**Comment by patrickedqvist** [comment]
@zackify Thank you for the quick reply and fix!
